name: "Deploy Calcualtor"

on:
  push:
    tags:
      - "V*.*.*"

env:
   PROJECT_PATH: Calculator/Calculator.csproj

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 5.0.*

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --no-build

       - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: Calculator/bin/Release/net5.0-windows/win-x64/publish/*

      # - name: Create a Release
      #   id: create_release
      #   uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "${{ github.ref }}"
      #     draft: true

      # - name: Upload Release Asset
      #   uses: shogo82148/actions-upload-release-asset@v1.6.2
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }} # default is ${{ github.token }}
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: Calculator/bin/Release/net5.0-windows/win-x64/publish/

