name: "Deploy Calcualtor"

on:
  push:
    tags:
      - "V*.*.*"

env:
   PROJECT_PATH: Calculator/Calculator.csproj
   PUBLISH_PATH: Calculator/bin/Release/net5.0-windows/win-x64/publish/

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 5.0.*

      - name: Restore Project
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build Project
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Publish Project
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --no-build

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip Binaries
        run: zip -qq -r binaries.zip dist node_modules package.json
        working-directory: ${{ env.PUBLISH_PATH }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: binaries.zip
          